version: "3.8"

services:
  db:
    image: postgres:15
    container_name: odoo-db-a
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data-a:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:16
    container_name: odoo-a
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_PORT=5432
      - ADMIN_PASSWORD=admin 
    ports:
      - "8069:8069"
    volumes:
      - odoo-data-a:/var/lib/odoo

volumes:
  db-data-a:
  odoo-data-a:

